Add spreadsheet v2 and pod documentation
microcovid/microcovid pull request #626
Opened 2021-01-07 05:22 UTC by blanchardjeremy

This pull request will contain the implementation of the "spreadsheet v2" documentation and pod/household documentation we've been working on in this [google doc](https://docs.google.com/document/d/1TfbcWjxr4kkzGhtGxcX9I4iJuVXrPFitWbTW6iDBzUU/edit#).

I'll have it as a draft pull request until it's ready for review.

2021-01-19 07:35 UTC, blanchardjeremy commented
@linesarefuzzy when I am ready for a review, I'd love it if you were one of the folks who gave the final version of the docs a read-through. If you have time. :)

2021-01-25 03:01 UTC, beshaya requested changes
I'm just reviewing the code + paper changes right now, not the markdown contents of the spreadsheet docs. I'm happy submitting this to the feature branch once requested changes are made.

2021-01-25 04:28 UTC, blanchardjeremy commented on src/posts/risk-questions.ts
> +The **Option A** questions rae simpler, but don't provide as many prompts to assist you. The **Option B** question are more detailed to help you think through various kinds of possible activities.
✅

2021-01-25 04:28 UTC, blanchardjeremy commented on src/posts/paper/13-q-and-a.ts
> +     You can check the annual rate of COVID infection for your region by looking up the number of cases in the past _day_; for states in the US, try [covidactnow.org](http://covidactnow.org). Divide
nuked

2021-01-25 04:31 UTC, blanchardjeremy commented on src/pages/Symptoms.tsx
> +const symptomPostMap: PostMap = {
Sure I can see the case for that.

2021-01-25 04:53 UTC, blanchardjeremy commented on src/pages/Symptoms.tsx
> +const symptomPostMap: PostMap = {
Done.

2021-01-25 04:54 UTC, blanchardjeremy commented on src/pages/Spreadsheet.tsx
> +export const SpreadsheetTOC = (): React.ReactElement => {
Can you say more about what you mean? This is following the same pattern as `Paper.tsx` and `PaperTOC`

What different file would you like it refactored into?

2021-01-25 05:02 UTC, blanchardjeremy commented on src/components/markdown/PaperPage.tsx
> +  rootTitle?: string
So after reviewing this, I see that it makes sense to remove `simplyLayout`. I don't see anything else that I would remove. 

If I refactored this into a separate file, I would actually keep `secitonTitle` as a feature. I think A is more clear than B:
![image](https://user-images.githubusercontent.com/32290/105663435-0efd2880-5e87-11eb-9283-91ad90513473.png)
![image](https://user-images.githubusercontent.com/32290/105663424-099fde00-5e87-11eb-9f38-cd6b84b83f16.png)

If I went with your approach of separating the files, I would
* Hardcode `sectionTitle` into the body of the function
* Remove `rootTitle` and put it back in hard-coded as "Table of Contents" in the body of the function
* Remove `showSectionNumbers`

These are pretty minor additions IMO. 

Whereas if I keep it as is, I don't have to replicate the entire body of the function and keep it up to date if we ever improve our page layout.

So... Those are my thoughts. If you still feel strongly about it, I'll just copy-paste it into its own file with these changes. Just seems odd to me.

2021-01-25 06:25 UTC, beshaya commented
That approach seems reasonable to me.

On Sun, Jan 24, 2021 at 9:03 PM Jeremy Blanchard <notifications@github.com>
wrote:

> *@blanchardjeremy* commented on this pull request.
> ------------------------------
>
> In src/components/markdown/PaperPage.tsx
> <https://github.com/microcovid/microcovid/pull/626#discussion_r563464729>:
>
> > @@ -11,7 +11,19 @@ export const MarkdownContents: React.FunctionComponent<{
>    posts: PostMap
>    id: string
>    allInOnePage?: boolean
> -}> = ({ posts, id, allInOnePage }) => {
> +  rootTitle?: string
>
> So after reviewing this, I see that it makes sense to remove simplyLayout.
> I don't see anything else that I would remove.
>
> If I refactored this into a separate file, I would actually keep
> secitonTitle as a feature. I think A is more clear than B:
> [image: image]
> <https://user-images.githubusercontent.com/32290/105663435-0efd2880-5e87-11eb-9283-91ad90513473.png>
> [image: image]
> <https://user-images.githubusercontent.com/32290/105663424-099fde00-5e87-11eb-9f38-cd6b84b83f16.png>
>
> If I went with your approach of separating the files, I would
>
>    - Hardcode sectionTitle into the body of the function
>    - Remove rootTitle and put it back in hard-coded as "Table of
>    Contents" in the body of the function
>    - Remove showSectionNumbers
>
> These are pretty minor additions IMO.
>
> Whereas if I keep it as is, I don't have to replicate the entire body of
> the function and keep it up to date if we ever improve our page layout.
>
> So... Those are my thoughts. If you still feel strongly about it, I'll
> just copy-paste it into its own file with these changes. Just seems odd to
> me.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/microcovid/microcovid/pull/626#discussion_r563464729>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABM25LJRY763K4622GYVXT3S3T3QNANCNFSM4VYPF45Q>
> .
>

2021-01-25 06:27 UTC, beshaya commented
I think that pattern isn't good, but I can clean it up later if you want to
keep it consistent in this PR.

On Sun, Jan 24, 2021 at 8:54 PM Jeremy Blanchard <notifications@github.com>
wrote:

> *@blanchardjeremy* commented on this pull request.
> ------------------------------
>
> In src/pages/Spreadsheet.tsx
> <https://github.com/microcovid/microcovid/pull/626#discussion_r563462722>:
>
> >      </>
>    )
>  }
>
> -export const Spreadsheet = (): React.ReactElement => {
> +export const SpreadsheetTOC = (): React.ReactElement => {
>
> Can you say more about what you mean? This is following the same pattern
> as Paper.tsx and PaperTOC
>
> What different file would you like it refactored into?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/microcovid/microcovid/pull/626#discussion_r563462722>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABM25LM6B55K52D5QEMEPM3S3T2QDANCNFSM4VYPF45Q>
> .
>

2021-01-25 17:44 UTC, merged