Handle volume risk multiplier thoughtfully when kissing (#620)
microcovid/microcovid pull request #644
Opened 2021-01-14 04:04 UTC by jy2wong

When kissing, take the worse of the kissing and volume multipliers. In
particular, this means that

* there is no bonus for not talking when you are kissing
* kissing and loud talking multipliers are not multiplied together when
  kissing

2021-01-14 06:54 UTC, beshaya requested changes
Please add a test case or two in data/__tests__/calculate.test.ts

2021-01-14 06:54 UTC, beshaya commented on src/data/calculate.ts
>      if (data.distance === 'intimate') {
This would probably be easier to parse as a switch statement.

2021-01-15 01:54 UTC, blanchardjeremy commented
I guess I'm curious how there is such an activity as "kissing + loud talking" ... It seems like it should really be two activities: 1 that you log as kissing and the other that you log as loud talking. I'm curious what you have in mind when you say that you could select both. What's the example scenario?

Thanks!

2021-01-15 18:00 UTC, jy2wong commented
> I guess I'm curious how there is such an activity as "kissing + loud talking" ... It seems like it should really be two activities: 1 that you log as kissing and the other that you log as loud talking. I'm curious what you have in mind when you say that you could select both. What's the example scenario?
> 
> Thanks!

I didn't have one in mind to start with (just wanted to address #620), but if pressed, I'd suggest a karaoke night date.

2021-01-15 19:14 UTC, beshaya commented
It's not so much that there's an activity where you *should* select both as
the calculator *lets* you select both. Possibly we should just remove the
talking dropdown?

On Fri, Jan 15, 2021 at 10:00 AM Jenny <notifications@github.com> wrote:

> I guess I'm curious how there is such an activity as "kissing + loud
> talking" ... It seems like it should really be two activities: 1 that you
> log as kissing and the other that you log as loud talking. I'm curious what
> you have in mind when you say that you could select both. What's the
> example scenario?
>
> Thanks!
>
> I didn't have one in mind to start with (just wanted to address #620
> <https://github.com/microcovid/microcovid/issues/620>), but if pressed,
> I'd suggest a karaoke night date.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/microcovid/microcovid/pull/644#issuecomment-761093505>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABM25LOEOVO726TEYNTNLFDS2B7EVANCNFSM4WB2E7SA>
> .
>

2021-01-15 22:31 UTC, beshaya commented
Catherio approved giving kissing the same multiplier as loud talking, if you want to include that here (ok in a follow-up as well)

2021-01-17 05:30 UTC, blanchardjeremy commented
My two cents: I'm in favor of removing the conversation volume when selecting kissing. And I'll let y'all make a final call.

2021-01-17 23:53 UTC, jy2wong commented
I removed the conversational volume question in the kissing scenario, but then the only precaution left is the indoor/outdoor/ventilation one, which doesn't even do anything (it just tells you that it's ignoring the value).

What about hiding the *entire* Precautions section if you're kissing?

2021-01-18 07:58 UTC, blanchardjeremy commented
That sounds right to me. I'd suggest we remove the warning about "outdoor doesn't apply when kissing" and re-add some notice that explicitly says "no precautions apply when kissing" ... so the user understands why everything else disappeared. 

Thoughts?

(Maybe just removing them is obvious enough)

2021-01-18 17:17 UTC, jy2wong commented
I don't think it's necessary to explain. I think new additions to the bare minimum reading path need to achieve/satisfy at least one of these:

* address surprise (make it easy to quickly answer natural questions)
* be a sufficiently common source of surprise to justify making everyone else read it
* drive helpful changes in behaviour
* build future intuition about how to model

I don't think kissing satisfies any of these.

2021-01-19 00:47 UTC, beshaya commented
Makes sense to me. The reason this was here in the first place was because
we didn't have kissing, only "cuddling" or "close" where the other
multipliers make sense.

On Mon, Jan 18, 2021 at 9:18 AM Jenny <notifications@github.com> wrote:

> I don't think it's necessary to explain. I think new additions to the bare
> minimum reading path need to achieve/satisfy at least one of these:
>
>    - address surprise (make it easy to quickly answer natural questions)
>    - be a sufficiently common source of surprise to justify making
>    everyone else read it
>    - drive helpful changes in behaviour
>    - build future intuition about how to model
>
> I don't think kissing satisfies any of these.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/microcovid/microcovid/pull/644#issuecomment-762378936>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABM25LJ5XOMWYOHT75RRBCDS2RUM5ANCNFSM4WB2E7SA>
> .
>

2021-01-19 02:35 UTC, jy2wong commented
Current version complete removes precautions section including the header during the kissing scenario and reworks translation string to specifically be about the close case and not the intimate case. Also made it show up for the other ventilation-related bonuses.

PTAL?

2021-01-19 04:36 UTC, beshaya requested changes

2021-01-19 04:36 UTC, beshaya commented on src/locales/en.json
> +      "no_close_bonus_environment": "Good environment choices are being ignored in the calculation. We are not confident that good ventilation or being outdoors strongly reduces the risk when people
Kind of awkward wording?

"Good things are being ignored"

Also, changing the json key will cause all existing translations to show the English until they are re-translated. I think it is preferable to show the current translations (keep "no_intimate_bonus_outdoors")

2021-01-19 07:14 UTC, beshaya approved these changes

2021-01-19 07:19 UTC, merged